"""empty message

Revision ID: ba29c8c688ce
Revises: d60c71a043ff
Create Date: 2021-04-21 17:50:00.282959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba29c8c688ce'
down_revision = 'd60c71a043ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('catering_service', sa.Text(), nullable=True))
    op.add_column('service', sa.Column('decoracion', sa.Text(), nullable=True))
    op.add_column('service', sa.Column('dj', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'dj')
    op.drop_column('service', 'decoracion')
    op.drop_column('service', 'catering_service')
    # ### end Alembic commands ###
