"""empty message

Revision ID: ee55ea7c08fb
Revises: 75c495c56a16
Create Date: 2021-04-26 15:25:31.580576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee55ea7c08fb'
down_revision = '75c495c56a16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('administrador', sa.Boolean(), nullable=True))
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('user', 'administrador')
    # ### end Alembic commands ###
